language: node_js
node_js:
  - "10"

before_install:
    - npm install -g hexo

install:
    - npm install

before_script:
    - git config --global user.name 'ross-oreto'
    - git config --global user.email 'ross.oreto@gmail.com'
    - sed -i'' "s~{GITHUB_ACCESS_TOKEN}~${GITHUB_ACCESS_TOKEN}~" _config.yml

script:
    - hexo generate --deploy